unpackaged/main/default/objects/Automation_Kill_Switch__c/Automation_Kill_Switch__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Per-automation kill switches. Add a Disable_[AutomationName]__c checkbox field for each specific automation (flow, batch, class) that needs an independent kill switch.</description>
    <label>Automation Kill Switch</label>
</CustomObject>

unpackaged/main/default/objects/Global_Kill_Switch__c/Global_Kill_Switch__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Master kill switch. When Disable All is checked, all automations using the trigger framework and kill switch checks are disabled.</description>
    <label>Global Kill Switch</label>
</CustomObject>

unpackaged/main/default/objects/Global_Kill_Switch__c/fields/Disable_All__c.field-meta.xml
<CustomField>
    <fullName>Disable_All__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Master kill switch. When checked, disables ALL automations that check kill switches.</description>
    <inlineHelpText>Check to disable all automations org-wide.</inlineHelpText>
    <label>Disable All</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Global_Kill_Switch__c/fields/Disable_Outbound_Emails__c.field-meta.xml
<CustomField>
    <fullName>Disable_Outbound_Emails__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Suppresses outbound emails from automations when checked. Use during data migrations or sandbox testing to prevent unintended emails to external recipients.</description>
    <inlineHelpText>Check to suppress outbound emails from automations.</inlineHelpText>
    <label>Disable Outbound Emails</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Object_Kill_Switch__c/Object_Kill_Switch__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Per-object kill switches. Add a Disable_[ObjectName]__c checkbox field for each object that has automations. When checked, all automations for that object are disabled.</description>
    <label>Object Kill Switch</label>
</CustomObject>

unpackaged/main/default/classes/KillSwitchHelper.cls
/**
 * Provides helper methods to check hierarchy custom setting kill switches.
 * Uses getInstance() (no SOQL) to read Global, Object, Automation, and Email kill switches.
 */
public with sharing class KillSwitchHelper {

    /**
     * Checks whether the global master kill switch is enabled.
     * @return true if Disable_All__c is checked at the user, profile, or org level
     */
    public static Boolean isGloballyDisabled() {
        Global_Kill_Switch__c settings = Global_Kill_Switch__c.getInstance();
        return settings != null && settings.Disable_All__c;
    }

    /**
     * Checks whether automation is disabled for a specific object.
     * @param objectName API name of the object (e.g., 'Account')
     * @return true if Disable_[objectName]__c is checked
     */
    public static Boolean isObjectDisabled(String objectName) {
        Object_Kill_Switch__c settings = Object_Kill_Switch__c.getInstance();
        if (settings == null) {
            return false;
        }
        try {
            Object fieldValue = settings.get('Disable_' + objectName + '__c');
            return fieldValue != null && (Boolean) fieldValue;
        } catch (Exception e) {
            return false;
        }
    }

    /**
     * Checks whether a specific named automation is disabled.
     * @param automationName The automation identifier (e.g., 'Lead_Assignment_Flow')
     * @return true if Disable_[automationName]__c is checked
     */
    public static Boolean isAutomationDisabled(String automationName) {
        Automation_Kill_Switch__c settings = Automation_Kill_Switch__c.getInstance();
        if (settings == null) {
            return false;
        }
        try {
            Object fieldValue = settings.get('Disable_' + automationName + '__c');
            return fieldValue != null && (Boolean) fieldValue;
        } catch (Exception e) {
            return false;
        }
    }

    /**
     * Checks whether outbound emails are disabled via the global kill switch.
     * @return true if Disable_Outbound_Emails__c is checked
     */
    public static Boolean isEmailDisabled() {
        Global_Kill_Switch__c settings = Global_Kill_Switch__c.getInstance();
        if (settings == null) {
            return false;
        }
        try {
            Object fieldValue = settings.get('Disable_Outbound_Emails__c');
            return fieldValue != null && (Boolean) fieldValue;
        } catch (Exception e) {
            return false;
        }
    }

    /**
     * Convenience method that checks global, object, and automation kill switches in order.
     * Short-circuits on the first enabled switch.
     * @param objectName API name of the object
     * @param automationName The automation identifier
     * @return true if any of the three kill switches is enabled
     */
    public static Boolean isDisabled(String objectName, String automationName) {
        if (isGloballyDisabled()) {
            return true;
        }
        if (isObjectDisabled(objectName)) {
            return true;
        }
        return isAutomationDisabled(automationName);
    }

}