unpackaged/main/default/objects/Automation_Kill_Switch__c/Automation_Kill_Switch__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Per-automation kill switches. Add a Disable_[AutomationName]__c checkbox field for each specific automation (flow, batch, class) that needs an independent kill switch.</description>
    <label>Automation Kill Switch</label>
</CustomObject>

unpackaged/main/default/objects/Error_Log__c/Error_Log__c.object-meta.xml
<CustomObject>
    <description>Stores error log records created by the Error Logging Framework via platform events.</description>
    <label>Error Log</label>
    <nameField>
        <displayFormat>ERR-{00000}</displayFormat>
        <label>Error Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Error_Log__c/fields/Class_Name__c.field-meta.xml
<CustomField>
    <fullName>Class_Name__c</fullName>
    <description>Apex class or Flow API name where the error occurred.</description>
    <label>Class Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Error_Log__c/fields/Error_Message__c.field-meta.xml
<CustomField>
    <fullName>Error_Message__c</fullName>
    <description>The error message text.</description>
    <label>Error Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Error_Log__c/fields/Logged_At__c.field-meta.xml
<CustomField>
    <fullName>Logged_At__c</fullName>
    <description>Timestamp from the platform event, representing when the error was originally logged.</description>
    <label>Logged At</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Error_Log__c/fields/Method_Name__c.field-meta.xml
<CustomField>
    <fullName>Method_Name__c</fullName>
    <description>Method name or Flow element where the error occurred.</description>
    <label>Method Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Error_Log__c/fields/Running_User__c.field-meta.xml
<CustomField>
    <fullName>Running_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The user who triggered the error.</description>
    <label>Running User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Error_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Error_Log__c/fields/Severity__c.field-meta.xml
<CustomField>
    <fullName>Severity__c</fullName>
    <description>Severity level of the error.</description>
    <label>Severity</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ERROR</fullName>
            </value>
            <value>
                <fullName>WARNING</fullName>
            </value>
            <value>
                <fullName>INFO</fullName>
            </value>
            <value>
                <fullName>DEBUG</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Error_Log__c/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <description>Source of the error.</description>
    <label>Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Apex</fullName>
            </value>
            <value>
                <fullName>Flow</fullName>
            </value>
            <value>
                <fullName>Integration</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Error_Log_Settings__c/Error_Log_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Controls error logging behavior: enable/disable logging, email notifications, retention, verbosity, and user-facing error messages.</description>
    <label>Error Log Settings</label>
</CustomObject>

unpackaged/main/default/objects/Error_Log_Settings__c/fields/Email_Recipients__c.field-meta.xml
<CustomField>
    <fullName>Email_Recipients__c</fullName>
    <description>Comma-separated list of email addresses to receive error notifications.</description>
    <inlineHelpText>Enter comma-separated email addresses for error notifications.</inlineHelpText>
    <label>Email Recipients</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Error_Log_Settings__c/fields/Enable_Email_Notifications__c.field-meta.xml
<CustomField>
    <fullName>Enable_Email_Notifications__c</fullName>
    <defaultValue>false</defaultValue>
    <description>When checked, sends email notifications to configured recipients when ERROR severity logs are created.</description>
    <inlineHelpText>Check to enable email notifications on errors.</inlineHelpText>
    <label>Enable Email Notifications</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Error_Log_Settings__c/fields/Enable_Error_Logging__c.field-meta.xml
<CustomField>
    <fullName>Enable_Error_Logging__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Master on/off switch for error logging. When unchecked, no error log events are published.</description>
    <inlineHelpText>Uncheck to disable all error logging.</inlineHelpText>
    <label>Enable Error Logging</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Error_Log_Settings__c/fields/Log_Retention_Days__c.field-meta.xml
<CustomField>
    <fullName>Log_Retention_Days__c</fullName>
    <defaultValue>90</defaultValue>
    <description>Number of days to retain error log records before the retention batch deletes them.</description>
    <inlineHelpText>Error logs older than this many days are deleted by the retention batch job.</inlineHelpText>
    <label>Log Retention Days</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Error_Log_Settings__c/fields/Verbosity_Level__c.field-meta.xml
<CustomField>
    <fullName>Verbosity_Level__c</fullName>
    <defaultValue>&quot;DEBUG&quot;</defaultValue>
    <description>Controls which severity levels are logged. ERROR = only errors. WARNING = warnings and errors. INFO = info, warnings, and errors. DEBUG = everything.</description>
    <inlineHelpText>Valid values: ERROR, WARNING, INFO, DEBUG. Controls which severity levels are logged. ERROR = only errors. WARNING = warnings and errors. INFO = info, warnings, and errors. DEBUG = everything.</inlineHelpText>
    <label>Verbosity Level</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Global_Kill_Switch__c/Global_Kill_Switch__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Master kill switch. When Disable All is checked, all automations using the trigger framework and kill switch checks are disabled.</description>
    <label>Global Kill Switch</label>
</CustomObject>

unpackaged/main/default/objects/Global_Kill_Switch__c/fields/Disable_All__c.field-meta.xml
<CustomField>
    <fullName>Disable_All__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Master kill switch. When checked, disables ALL automations that check kill switches.</description>
    <inlineHelpText>Check to disable all automations org-wide.</inlineHelpText>
    <label>Disable All</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Global_Kill_Switch__c/fields/Disable_Outbound_Emails__c.field-meta.xml
<CustomField>
    <fullName>Disable_Outbound_Emails__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Suppresses outbound emails from automations when checked. Use during data migrations or sandbox testing to prevent unintended emails to external recipients.</description>
    <inlineHelpText>Check to suppress outbound emails from automations.</inlineHelpText>
    <label>Disable Outbound Emails</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Object_Kill_Switch__c/Object_Kill_Switch__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Per-object kill switches. Add a Disable_[ObjectName]__c checkbox field for each object that has automations. When checked, all automations for that object are disabled.</description>
    <label>Object Kill Switch</label>
</CustomObject>

unpackaged/main/default/objects/Validation_Kill_Switch__c/Validation_Kill_Switch__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Per-object validation rule kill switches. Add a Disable_[ObjectName]__c checkbox field for each object that has validation rules you need to bypass. When checked, validation rules that include the $Setup formula check for this setting are bypassed.</description>
    <label>Validation Kill Switch</label>
</CustomObject>

unpackaged/main/default/classes/TestDataFactory.cls
@IsTest
public class TestDataFactory {

    public static void setupErrorLogSettings() {
        setupErrorLogSettings(true, false, null, 90, 'DEBUG');
    }

    public static void setupErrorLogSettings(Boolean enableLogging, Boolean enableEmail,
                                              String emailRecipients, Integer retentionDays,
                                              String verbosity) {
        Error_Log_Settings__c settings = Error_Log_Settings__c.getOrgDefaults();
        settings.Enable_Error_Logging__c = enableLogging;
        settings.Enable_Email_Notifications__c = enableEmail;
        settings.Email_Recipients__c = emailRecipients;
        settings.Log_Retention_Days__c = retentionDays;
        settings.Verbosity_Level__c = verbosity;
        upsert settings;
    }

    public static void setupKillSwitches() {
        Global_Kill_Switch__c globalKs = Global_Kill_Switch__c.getOrgDefaults();
        globalKs.Disable_All__c = false;
        globalKs.Disable_Outbound_Emails__c = false;
        upsert globalKs;

        Object_Kill_Switch__c objectKs = Object_Kill_Switch__c.getOrgDefaults();
        upsert objectKs;

        Automation_Kill_Switch__c autoKs = Automation_Kill_Switch__c.getOrgDefaults();
        upsert autoKs;

        Validation_Kill_Switch__c validationKs = Validation_Kill_Switch__c.getOrgDefaults();
        upsert validationKs;
    }

    public static void enableGlobalKillSwitch() {
        Global_Kill_Switch__c globalKs = Global_Kill_Switch__c.getOrgDefaults();
        globalKs.Disable_All__c = true;
        upsert globalKs;
    }

    public static void enableEmailKillSwitch() {
        Global_Kill_Switch__c globalKs = Global_Kill_Switch__c.getOrgDefaults();
        globalKs.Disable_Outbound_Emails__c = true;
        upsert globalKs;
    }

    public static void enableValidationKillSwitch(String objectName) {
        Validation_Kill_Switch__c validationKs = Validation_Kill_Switch__c.getOrgDefaults();
        validationKs.put('Disable_' + objectName + '__c', true);
        upsert validationKs;
    }

    public static void enableObjectKillSwitch(String objectName) {
        Object_Kill_Switch__c objectKs = Object_Kill_Switch__c.getOrgDefaults();
        objectKs.put('Disable_' + objectName + '__c', true);
        upsert objectKs;
    }

    public static void enableAutomationKillSwitch(String automationName) {
        Automation_Kill_Switch__c autoKs = Automation_Kill_Switch__c.getOrgDefaults();
        autoKs.put('Disable_' + automationName + '__c', true);
        upsert autoKs;
    }

    public static Error_Log__c createErrorLog(String className, String severity) {
        Error_Log__c log = new Error_Log__c(
            Class_Name__c = className,
            Method_Name__c = 'testMethod',
            Error_Message__c = 'Test error message',
            Severity__c = severity,
            Source__c = 'Apex',
            Logged_At__c = Datetime.now(),
            Running_User__c = UserInfo.getUserId()
        );
        insert log;
        return log;
    }

    public static List<Error_Log__c> createErrorLogs(Integer count) {
        List<Error_Log__c> logs = new List<Error_Log__c>();
        for (Integer i = 0; i < count; i++) {
            logs.add(new Error_Log__c(
                Class_Name__c = 'TestClass' + i,
                Method_Name__c = 'testMethod',
                Error_Message__c = 'Test error message ' + i,
                Severity__c = 'ERROR',
                Source__c = 'Apex',
                Logged_At__c = Datetime.now(),
                Running_User__c = UserInfo.getUserId()
            ));
        }
        insert logs;
        return logs;
    }
}